   var dependencies = {
    links:
      [
            { "source" : "BridgeAnnotation", "dest" : "MKPinAnnotationView" },
            { "source" : "CustomAnnotation", "dest" : "CustomAnnotationView" },
            { "source" : "CustomAnnotationView", "dest" : "MKAnnotationView" },
            { "source" : "main", "dest" : "AppDelegate" },
            { "source" : "MapViewController", "dest" : "BridgeAnnotation" },
            { "source" : "MapViewController", "dest" : "CustomAnnotation" },
            { "source" : "MapViewController", "dest" : "MKUserLocation" },
            { "source" : "MapViewController", "dest" : "SFAnnotation" },
            { "source" : "SFAnnotation", "dest" : "MKAnnotationView" },
            { "source" : "BridgeAnnotation", "dest" : "MKAnnotationView" },
            { "source" : "BridgeAnnotation", "dest" : "MKMapView" },
            { "source" : "BridgeAnnotation", "dest" : "MKMapCamera" },
            { "source" : "BridgeAnnotation", "dest" : "MKUserLocation" },
            { "source" : "BridgeAnnotation", "dest" : "CLLocation" },
            { "source" : "BridgeAnnotation", "dest" : "CLFloor" },
            { "source" : "BridgeAnnotation", "dest" : "CLHeading" },
            { "source" : "CustomAnnotation", "dest" : "MKAnnotationView" },
            { "source" : "CustomAnnotation", "dest" : "MKMapView" },
            { "source" : "CustomAnnotation", "dest" : "MKMapCamera" },
            { "source" : "CustomAnnotation", "dest" : "MKUserLocation" },
            { "source" : "CustomAnnotation", "dest" : "CLLocation" },
            { "source" : "CustomAnnotation", "dest" : "CLFloor" },
            { "source" : "CustomAnnotation", "dest" : "CLHeading" },
            { "source" : "CustomAnnotationView", "dest" : "CustomAnnotation" },
            { "source" : "MapViewController", "dest" : "MKMapView" },
            { "source" : "MapViewController", "dest" : "MKMapCamera" },
            { "source" : "MapViewController", "dest" : "MKUserLocation" },
            { "source" : "MapViewController", "dest" : "CLLocation" },
            { "source" : "MapViewController", "dest" : "CLFloor" },
            { "source" : "MapViewController", "dest" : "CLHeading" },
            { "source" : "MapViewController", "dest" : "MKAnnotationView" },
            { "source" : "MapViewController", "dest" : "SFAnnotation" },
            { "source" : "MapViewController", "dest" : "BridgeAnnotation" },
            { "source" : "MapViewController", "dest" : "CustomAnnotation" },
            { "source" : "MapViewController", "dest" : "DetailViewController" },
            { "source" : "SFAnnotation", "dest" : "MKAnnotationView" },
            { "source" : "SFAnnotation", "dest" : "MKMapView" },
            { "source" : "SFAnnotation", "dest" : "MKMapCamera" },
            { "source" : "SFAnnotation", "dest" : "MKUserLocation" },
            { "source" : "SFAnnotation", "dest" : "CLLocation" },
            { "source" : "SFAnnotation", "dest" : "CLFloor" },
            { "source" : "SFAnnotation", "dest" : "CLHeading" },
         ]
    }
  ;
